CREATE TABLE DEVELOPERS(
   ID INT NOT NULL AUTO_INCREMENT ,
   FIRST_NAME VARCHAR(50) DEFAULT NULL,
   LAST_NAME VARCHAR(50) DEFAULT NULL,
   status int(4) NOT NULL,
   SPECIALTY INT NOT NULL,
   PRIMARY KEY(ID)
);