CREATE TABLE IF NOT EXISTS DEVELOPERS(
   ID INT NOT NULL AUTO_INCREMENT ,
   FIRST_NAME VARCHAR(50) DEFAULT NULL,
   LAST_NAME VARCHAR(50) DEFAULT NULL,
   status SMALLINT NOT NULL,
   SPECIALTY INT NOT NULL,

   PRIMARY KEY(ID),

   foreign key (SPECIALTY) references specialties(id) on delete cascade
);